# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

acceleratedAcademy = School.create(name:"Accelerated Academy", district:"Seattle", description:"High school")
meadowsUniversity= School.create(name:"Meadows University", district:"San Francisco", description:"University")
westviewKindergarten= School.create(name:"Westview Kindergarten", district:"San Francisco", description:"Preschool")
tulipTree= School.create(name:"Tulip Tree", district:"San Francisco", description:"High school")
greenSprout= School.create(name:"Green Sprout", district:"Seattle", description:"High school")
countryDaySchool= School.create(name:"Country Day School", district:"Seattle", description:"Day School")
wheePreschool= School.create(name:"Whee Preschool", district:"San Francisco", description:"Preschool")
creatingChampions= School.create(name:"Creating Champions", district:"Seattle", description:"Academy")
prioritizePrimary= School.create(name:"Prioritize Primary", district:"Seattle", description:"Academy")
eastwoodHigh= School.create(name:"Eastwood High", district:"Seattle", description:"English school")

john = User.create(name: 'John')
mary = User.create(name: 'Mary')
jane = User.create(name: 'Jane')
scott = User.create(name: 'Scott')
zana = User.create(name: 'Zana')
gabriel = User.create(name: 'Gabriel')
nicole = User.create(name: 'Nicole')
gary = User.create(name: 'Gary')
brandon = User.create(name: 'Brandon')
josh = User.create(name: 'Josh')
candace = User.create(name: 'Candace')
erika = User.create(name: 'Erika')
david = User.create(name: 'David')
lena = User.create(name: 'Lena')
jo = User.create(name: 'Jo')
delilah = User.create(name: 'Delilah')
jimmy = User.create(name: 'Jimmy')
madelyn = User.create(name: 'Madelyn')
leo = User.create(name: 'Leo')
bella = User.create(name: 'Bella')
lexi = User.create(name: 'Lexi')
robin = User.create(name: 'Robin')
laura = User.create(name: 'Laura')
emily = User.create(name: 'Emily')
sheila = User.create(name: 'Sheila')
mackenzie = User.create(name: 'Mackenzie')
jetzen = User.create(name: 'Jetzen')
rheanne = User.create(name: 'Rheanne')
christabelle = User.create(name: 'Christabelle')
anna = User.create(name: 'Anna')
amber = User.create(name: 'Amber')
julian = User.create(name: 'Julian')
mark = User.create(name: 'Mark')
jason = User.create(name: 'Jason')

